.MODEL SMALL
.STACK 200H
.CODE

START:
	MOV AH, 02H	; AH = 02H, WRITE CHARACTER TO STANDARD OUTPUT
	MOV DL, 69	; DL = character to write
	INT 21H

	MOV AH, 4CH	; AH = 4CH, EXIT - TERMINATE WITH RETURN CODE 
	MOV AL, 00H	; AL = return code
	INT 21H

END START
